version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Dataset-S3-Service-stack"
s3_bucket = "myob-pgol-pipelinedeployment"
s3_prefix = "sam-datasets3service-package"
region = "ap-southeast-2"
profile = "test"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
