version: 0.2
env:
phases:
  pre_build:
    commands:
      - echo Pre-Build started on `date`
      - pwsh $CODEBUILD_SRC_DIR/bin/lambda_deploy_to_prod/prebuild.ps1
  build:
    commands:
      - echo Build started on `date`
      - pwsh $CODEBUILD_SRC_DIR/bin/lambda_deploy_to_prod/build.ps1
