version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Entered the install phase
      - pwsh $CODEBUILD_SRC_DIR/bin/lambda_build/prebuild.ps1
  build:
    commands:
      - echo Build started on `date`
      - pwsh $CODEBUILD_SRC_DIR/bin/lambda_build/build.ps1
artifacts:
  files:
    - '.aws-sam/**/*'
    - 'bin/**/*'
    - 'etc/buildspec/*'
    - './*'
  

